name: build
on:
  push:
    branches: [master]
    paths-ignore: 
      - "**.md"

  pull_request:
    branches: [master]
    paths-ignore: 
      - "**.md"

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]

    steps:
      - uses: actions/checkout@v1
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - uses: php-actions/composer@v5

      - name: phpunit
        uses: php-actions/phpunit@v2
      
      - name: codecov test
        uses: codecov/codecov-action@v1
        with: 
          ref: ${{ github.head_ref }}
          token: ${{ secrets.CODECOV_TOKEN }} 
          verbose: true 
    
    